version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
        command:
            - php-fpm
        depends_on:
            - mysql
            - redis

    web:
        image: nginx:latest
        container_name: web
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - laravel
        depends_on:
            - php

    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: user
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
        ports:
            - "3306:3306"
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
